### ISSUE TITLE
Conversions to string and back are culture dependant

### ISSUE THREAD

**Issue by NotestQ** [RugbugRedfern/Mycelium-Networking-For-Content-Warning#7]
## What is the problem?
C# converts numbers to string and vice-versa based on locale, if player A from one country sets the data and player B from another country with a different decimal point interpretation gets the data the numbers might get converted in a "wrong" way

## What was expected to happen?
Mycelium should get the data the same way we set them, which would be culture independent

## How do I reproduce this issue?
Setting lobby data in a [decimal comma locale](https://en.wikipedia.org/wiki/Decimal_separator#Countries_using_decimal_comma) and retrieving the lobby data in a [decimal point locale](https://en.wikipedia.org/wiki/Decimal_separator#Countries_using_decimal_point) would reproduce the issue

## Where is this present?
This bug seems to be present in LobbyData and PlayerData, RPCs aren't converted to string and back so that wouldn't and shouldn't have the issue

## Potential fixes?
Calling `ChangeType` and `ToString` with `CultureInfo.InvariantCulture` as the CultureInfo parameter

**Comment by RugbugRedfern** [comment]
Fixed in v1.0.14
